### ISSUE TITLE
Question on iOS vs Web

### ISSUE THREAD

**Issue by surayashivji** [CarterAppleton/Spotify-Web-Wrapper#1]
What's the advantage of creating a web wrapper vs using the native iOS SDK?

Thank you!

**Comment by CarterAppleton** [comment]
I was looking into the Spotify API and found that the Web API provided significantly more functionality than the native API. It looks like Spotify has improved their native API since then, but it's still in beta and "likely to change significantly and without warning." I think the Web API would still be a better choice as it's probably more stable.
